// frontend/src/partials/dashboard/DashboardCard07.vue
<template>
  <div class="flex flex-col col-span-full sm:col-span-6 bg-white dark:bg-gray-800 shadow-sm rounded-xl">
    <header class="px-5 py-4 border-b border-gray-100 dark:border-gray-700/60 flex items-center justify-between">
      <h2 class="font-semibold text-gray-800 dark:text-gray-100">
        Toco Weather Station
      </h2>
      <div class="flex items-center">
        <select 
          class="p-2 border rounded text-sm mr-2"
          v-model="selectedMetric"
        >
          <option v-for="option in metricOptions" :key="option.value" :value="option.value">
            {{ option.label }}
          </option>
        </select>
        <div class="text-sm text-gray-500">
          Last updated: {{ lastUpdated ? lastUpdated.toLocaleTimeString() : 'Never' }}
        </div>
      </div>
    </header>
    <div v-if="loading && tocoTimeline.length === 0" class="flex justify-center items-center h-64">Loading...</div>
    <div v-else-if="error && tocoTimeline.length === 0" class="text-center text-red-500">{{ error }}</div>
    <div v-else>
      <RealtimeChart v-if="chartData" :data="chartData" :width="595" :height="248" :selectedMetric="selectedMetric" stationName="Toco" />
      <div v-else class="flex items-center justify-center h-64">
        <div class="text-gray-500">No timeline data available for the selected metric</div>
      </div>
      <div class="text-xs text-gray-400 text-right mt-2 pr-4">
        Last fetched: {{ lastFetched.toLocaleTimeString() }}
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, watch } from 'vue';
import axios from 'axios';
import RealtimeChart from '../../charts/RealtimeChart.vue';
import { tailwindConfig, hexToRGB } from '../../utils/Utils';

export default {
  name: 'DashboardCard07',
  components: {
    RealtimeChart,
  },
  setup() {
    const tocoTimeline = ref([]);
    const selectedMetric = ref('temperature');
    const chartData = ref(null);
    const error = ref(null);
    const loading = ref(true);
    const lastUpdated = ref(null);
    const lastFetched = ref(new Date());

    const metricOptions = [
      { value: 'temperature', label: 'Temperature (°C)' },
      { value: 'wind_speed', label: 'Wind Speed (km/h)' },
      { value: 'wind_direction', label: 'Wind Direction (°)' },
      { value: 'humidity', label: 'Humidity (%)' },
      { value: 'precipitation', label: 'Precipitation (mm)' },
      { value: 'solar_radiation', label: 'Solar Radiation (W/m²)' },
      { value: 'uv_index', label: 'UV Index' },
      { value: 'barometric_pressure', label: 'Barometric Pressure (hPa)' }
    ];

    const fetchData = async () => {
      try {
        loading.value = true;
        const response = await axios.get('http://127.0.0.1:8000/api/weather_stations/', {
          headers: { 'Accept': 'application/json' }
        });
        console.log('Raw API response:', response.data);
        
        if (Array.isArray(response.data) && response.data.length > 0) {
          const tocoDataPoints = response.data.filter(station => station.name.toLowerCase() === 'toco');
          if (tocoDataPoints.length > 0) {
            console.log('Toco data points found:', tocoDataPoints);
            tocoTimeline.value = tocoDataPoints.sort((a, b) => new Date(a.recorded_at) - new Date(b.recorded_at)).slice(-24);
            lastUpdated.value = new Date(tocoDataPoints[tocoDataPoints.length - 1].recorded_at);
          } else {
            console.error('No Toco data points found in the data');
            error.value = 'No Toco data points found in the data';
          }
        } else {
          console.error('Unexpected data format or empty array');
          error.value = 'Unexpected data format or no data available';
        }
        lastFetched.value = new Date();
      } catch (err) {
        console.error('Error fetching data:', err);
        error.value = 'Error fetching data: ' + err.message;
      } finally {
        loading.value = false;
      }
    };

    onMounted(() => {
      fetchData();
      const interval = setInterval(fetchData, 3600000); // Update every hour
      return () => clearInterval(interval);
    });

    watch([tocoTimeline, selectedMetric], () => {
      if (tocoTimeline.value.length > 0 && selectedMetric.value) {
        const labels = tocoTimeline.value.map(entry => new Date(entry.recorded_at).toLocaleTimeString());
        const data = tocoTimeline.value.map(entry => parseFloat(entry[selectedMetric.value]));
        
        chartData.value = {
          labels: labels,
          datasets: [{
            data: data,
            fill: true,
            backgroundColor: `rgba(${hexToRGB(tailwindConfig().theme.colors.yellow[500])}, 0.08)`,
            borderColor: tailwindConfig().theme.colors.yellow[500],
            borderWidth: 2,
            tension: 0,
            pointRadius: 0,
            pointHoverRadius: 3,
            pointBackgroundColor: tailwindConfig().theme.colors.yellow[500],
            pointHoverBackgroundColor: tailwindConfig().theme.colors.yellow[500],
            pointBorderWidth: 0,
            pointHoverBorderWidth: 0,          
            clip: 20,
          }],
        };
      } else {
        chartData.value = null;
      }
    });

    return {
      tocoTimeline,
      selectedMetric,
      chartData,
      error,
      loading,
      lastUpdated,
      lastFetched,
      metricOptions,
    };
  },
};
</script>

<style scoped>
/* Add any scoped styles here */
</style>

// frontend/src/partials/dashboard/DashboardCard07.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';

function DashboardCard07() {
  const [weatherStations, setWeatherStations] = useState([]);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState(new Date());

  useEffect(() => {
    axios.get('http://127.0.0.1:8000/api/weather_stations/', {
      headers: {
        'Accept': 'application/json',
      }
    })
      .then(response => {
        if (Array.isArray(response.data)) {
          setWeatherStations(response.data);
          setLastUpdated(new Date());
        } else {
          setError('Unexpected data format: Expected an array');
        }
      })
      .catch(error => {
        setError('Error fetching data: ' + error.message);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="col-span-full xl:col-span-12 bg-white dark:bg-gray-800 shadow-lg rounded-xl p-8">
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-blue-500"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="col-span-full xl:col-span-12 bg-white dark:bg-gray-800 shadow-lg rounded-xl p-8">
        <div className="text-center py-8 text-red-600 font-semibold">
          <svg className="w-12 h-12 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>
          Error: {error}
        </div>
      </div>
    );
  }

  return (
    <div className="col-span-full xl:col-span-12 bg-white dark:bg-gray-800 shadow-lg rounded-xl overflow-hidden">
      <header className="px-5 py-4 border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-700">
        <div className="flex justify-between items-center">
          <h2 className="font-semibold text-gray-800 dark:text-gray-100">All Weather Stations</h2>
          <div className="text-sm text-gray-500 dark:text-gray-400">
            Last updated: {lastUpdated.toLocaleDateString()} at {lastUpdated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </div>
        </div>
      </header>
      <div className="p-3">
        <div className="overflow-x-auto">
          <table className="table-auto w-full">
            <thead className="text-xs uppercase text-gray-400 dark:text-gray-500 bg-gray-50 dark:bg-gray-700 rounded-sm">
              <tr>
                <th className="p-2"><div className="font-semibold text-left">Weather Station</div></th>
                <th className="p-2"><div className="font-semibold text-center">Temperature</div></th>
                <th className="p-2"><div className="font-semibold text-center">Wind Speed</div></th>
                <th className="p-2"><div className="font-semibold text-center">Wind Direction</div></th>
                <th className="p-2"><div className="font-semibold text-center">Humidity</div></th>
                <th className="p-2"><div className="font-semibold text-center">Precipitation</div></th>
                <th className="p-2"><div className="font-semibold text-center">Solar Radiation</div></th>
                <th className="p-2"><div className="font-semibold text-center">UV Index</div></th>
                <th className="p-2"><div className="font-semibold text-center">Barometric Pressure</div></th>
              </tr>
            </thead>
            <tbody className="text-sm divide-y divide-gray-100 dark:divide-gray-700">
              {weatherStations.length > 0 ? (
                weatherStations.map((station, index) => (
                  <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition duration-150">
                    <td className="p-2">
                      <div className="flex items-center">
                        <div className="text-gray-800 dark:text-gray-100 font-medium">{station.name}</div>
                      </div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-green-500 font-semibold">{station.temperature}°C</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-blue-500 font-semibold">{station.wind_speed} km/h</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-purple-500 font-semibold">{station.wind_direction}°</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-yellow-500 font-semibold">{station.humidity}%</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-blue-400 font-semibold">{station.precipitation} mm</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-orange-500 font-semibold">{station.solar_radiation} W/m²</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-pink-500 font-semibold">{station.uv_index}</div>
                    </td>
                    <td className="p-2">
                      <div className="text-center text-indigo-500 font-semibold">{station.barometric_pressure} hPa</div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="9" className="text-center p-4 text-gray-500 dark:text-gray-400">No data available</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default DashboardCard07;
